server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    # Esta línea le dice a Lavalink que descargue el plugin anti-bloqueos de YouTube
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false # ¡APAGAMOS EL YOUTUBE VIEJO Y ROTO!
      soundcloud: true
      twitch: false
      vimeo: false
      http: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
    - WEB
    - M_WEB
    - WEBEMBEDDED
    - TVHTML5EMBEDDED
  lavasrc:
    sources:
      spotify: true   
      applemusic: false
      deezer: false
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      countryCode: "ES"